#
# Copyright (c) 2019 Nordic Semiconductor ASA
#
# SPDX-License-Identifier: LicenseRef-Nordic-5-Clause
#
CONFIG_NCS_SAMPLES_DEFAULTS=y
CONFIG_ESB=y
CONFIG_DK_LIBRARY=y
CONFIG_CLOCK_CONTROL=y

CONFIG_ESB_MAX_PAYLOAD_LENGTH=72
CONFIG_ESB_FAST_SWITCHING=y
CONFIG_ESB_FAST_CHANNEL_SWITCHING=y
# CONFIG_ESB_NEVER_DISABLE_TX=y
# CONFIG_NRFX_DPPI10=y

# CONFIG_FLASH=y
# CONFIG_FLASH_MAP=y
# CONFIG_FLASH_LOAD_OFFSET=0x10000
# CONFIG_SPI=y

# 低频时钟：使用内部 RC，而不是外部 32.768 kHz 晶振
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_XTAL=n
CONFIG_CLOCK_CONTROL_NRF_K32SRC_SYNTH=n
# 根据需求选择 RC 精度和校准策略（可选，但推荐）
CONFIG_CLOCK_CONTROL_NRF_K32SRC_500PPM=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC_CALIBRATION=y
CONFIG_CLOCK_CONTROL_NRF_CALIBRATION_LF_ALWAYS_ON=y
